sudo: required
language: generic

services:
    - docker


before_install:
    - docker build -t theomjones/docker-react -f Dockerfile.dev .

    # docker run -e CI=true USERNAME/docker-react npm run test
    # language: generic 

script:
    - docker run -e CI=true theomjones/docker-react npm run test